package it.polimi.ingsw.model.player;

public enum PlayerState {
    WAITING,
    ASSISTANTPHASE,
    STUDENTPHASE,
    MOTHERNATUREPHASE,
    CLOUDPHASE,
    DISCONNECTED,
    CHARACTHERISLANDPHASE,
    CHARACTHERSTUDENTSPHASE,
    RECONNECTED
}
